kind = "api"
previewPath = "/"
title = "VolumeSplit"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "API Server"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace/artifacts/volumesplit && VS_DATA=./data uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
